package warrior;

import battlecode.common.Direction;
import battlecode.common.GameActionException;
import battlecode.common.MapLocation;
import battlecode.common.RobotController;

// Generated by scripts/dijkstra.py
// Based on Malott Fat Cats's 2021 pathfinding
// Malott Fat Cats's 2021 post-mortem: https://www.battlecode.org/files/postmortem-2021-malott-fat-cats.pdf
public class Dijkstra6 {
    private static RobotController rc;

    private static int mapWidth;
    private static int mapHeight;

    private static MapLocation myLocation;
    private static int myX;
    private static int myY;
    private static int xOffset;
    private static int yOffset;

    private static MapLocation location1;
    private static double distance1;
    private static Direction direction1;
    private static double remainingDistance1;
    private static double totalScore1;
    private static MapLocation location2;
    private static double distance2;
    private static Direction direction2;
    private static double remainingDistance2;
    private static double totalScore2;
    private static MapLocation location3;
    private static double distance3;
    private static Direction direction3;
    private static double remainingDistance3;
    private static double totalScore3;
    private static MapLocation location4;
    private static double distance4;
    private static Direction direction4;
    private static double remainingDistance4;
    private static double totalScore4;
    private static MapLocation location5;
    private static double distance5;
    private static Direction direction5;
    private static double remainingDistance5;
    private static double totalScore5;
    private static MapLocation location6;
    private static double distance6;
    private static Direction direction6;
    private static double remainingDistance6;
    private static double totalScore6;
    private static MapLocation location7;
    private static double distance7;
    private static Direction direction7;
    private static double remainingDistance7;
    private static double totalScore7;
    private static MapLocation location8;
    private static double distance8;
    private static Direction direction8;
    private static double remainingDistance8;
    private static double totalScore8;
    private static MapLocation location9;
    private static double distance9;
    private static Direction direction9;
    private static double remainingDistance9;
    private static double totalScore9;
    private static MapLocation location12;
    private static double distance12;
    private static Direction direction12;
    private static double remainingDistance12;
    private static double totalScore12;
    private static MapLocation location15;
    private static double distance15;
    private static Direction direction15;
    private static double remainingDistance15;
    private static double totalScore15;
    private static MapLocation location18;
    private static double distance18;
    private static Direction direction18;
    private static double remainingDistance18;
    private static double totalScore18;
    private static MapLocation location10;
    private static double distance10;
    private static Direction direction10;
    private static double remainingDistance10;
    private static double totalScore10;
    private static MapLocation location11;
    private static double distance11;
    private static Direction direction11;
    private static double remainingDistance11;
    private static double totalScore11;
    private static MapLocation location13;
    private static double distance13;
    private static Direction direction13;
    private static double remainingDistance13;
    private static double totalScore13;
    private static MapLocation location14;
    private static double distance14;
    private static Direction direction14;
    private static double remainingDistance14;
    private static double totalScore14;
    private static MapLocation location16;
    private static double distance16;
    private static Direction direction16;
    private static double remainingDistance16;
    private static double totalScore16;
    private static MapLocation location17;
    private static double distance17;
    private static Direction direction17;
    private static double remainingDistance17;
    private static double totalScore17;
    private static MapLocation location19;
    private static double distance19;
    private static Direction direction19;
    private static double remainingDistance19;
    private static double totalScore19;
    private static MapLocation location20;
    private static double distance20;
    private static Direction direction20;
    private static double remainingDistance20;
    private static double totalScore20;

    private static double weight;

    private static double currentDistance;

    private static double score5;
    private static double score6;
    private static double score7;
    private static double score8;
    private static double score9;
    private static double score12;
    private static double score15;
    private static double score18;
    private static double score10;
    private static double score11;
    private static double score13;
    private static double score14;
    private static double score16;
    private static double score17;
    private static double score19;

    private static double maxScore;

    public Dijkstra6(RobotController rc) {
        Dijkstra6.rc = rc;

        mapWidth = rc.getMapWidth();
        mapHeight = rc.getMapHeight();
    }

    public Direction getBestDirection(MapLocation target, Direction blockedDirection) throws GameActionException {
        myLocation = rc.getLocation();
        myX = myLocation.x;
        myY = myLocation.y;
        xOffset = mapWidth - myX;
        yOffset = mapHeight - myY;

        location1 = rc.adjacentLocation(Direction.WEST);
        distance1 = 1_000_000.0;
        remainingDistance1 = location1.distanceSquaredTo(target);
        totalScore1 = distance1 + remainingDistance1;
        location2 = rc.adjacentLocation(Direction.EAST);
        distance2 = 1_000_000.0;
        remainingDistance2 = location2.distanceSquaredTo(target);
        totalScore2 = distance2 + remainingDistance2;
        location3 = rc.adjacentLocation(Direction.SOUTH);
        distance3 = 1_000_000.0;
        remainingDistance3 = location3.distanceSquaredTo(target);
        totalScore3 = distance3 + remainingDistance3;
        location4 = rc.adjacentLocation(Direction.NORTH);
        distance4 = 1_000_000.0;
        remainingDistance4 = location4.distanceSquaredTo(target);
        totalScore4 = distance4 + remainingDistance4;
        location5 = rc.adjacentLocation(Direction.SOUTHWEST);
        distance5 = 1_000_000.0;
        remainingDistance5 = location5.distanceSquaredTo(target);
        totalScore5 = distance5 + remainingDistance5;
        location6 = rc.adjacentLocation(Direction.NORTHWEST);
        distance6 = 1_000_000.0;
        remainingDistance6 = location6.distanceSquaredTo(target);
        totalScore6 = distance6 + remainingDistance6;
        location7 = rc.adjacentLocation(Direction.SOUTHEAST);
        distance7 = 1_000_000.0;
        remainingDistance7 = location7.distanceSquaredTo(target);
        totalScore7 = distance7 + remainingDistance7;
        location8 = rc.adjacentLocation(Direction.NORTHEAST);
        distance8 = 1_000_000.0;
        remainingDistance8 = location8.distanceSquaredTo(target);
        totalScore8 = distance8 + remainingDistance8;
        location9 = location1.add(Direction.WEST);
        distance9 = 1_000_000.0;
        remainingDistance9 = location9.distanceSquaredTo(target);
        totalScore9 = distance9 + remainingDistance9;
        location12 = location2.add(Direction.EAST);
        distance12 = 1_000_000.0;
        remainingDistance12 = location12.distanceSquaredTo(target);
        totalScore12 = distance12 + remainingDistance12;
        location15 = location3.add(Direction.SOUTH);
        distance15 = 1_000_000.0;
        remainingDistance15 = location15.distanceSquaredTo(target);
        totalScore15 = distance15 + remainingDistance15;
        location18 = location4.add(Direction.NORTH);
        distance18 = 1_000_000.0;
        remainingDistance18 = location18.distanceSquaredTo(target);
        totalScore18 = distance18 + remainingDistance18;
        location10 = location1.add(Direction.SOUTHWEST);
        distance10 = 1_000_000.0;
        remainingDistance10 = location10.distanceSquaredTo(target);
        totalScore10 = distance10 + remainingDistance10;
        location11 = location1.add(Direction.NORTHWEST);
        distance11 = 1_000_000.0;
        remainingDistance11 = location11.distanceSquaredTo(target);
        totalScore11 = distance11 + remainingDistance11;
        location13 = location2.add(Direction.SOUTHEAST);
        distance13 = 1_000_000.0;
        remainingDistance13 = location13.distanceSquaredTo(target);
        totalScore13 = distance13 + remainingDistance13;
        location14 = location2.add(Direction.NORTHEAST);
        distance14 = 1_000_000.0;
        remainingDistance14 = location14.distanceSquaredTo(target);
        totalScore14 = distance14 + remainingDistance14;
        location16 = location3.add(Direction.SOUTHWEST);
        distance16 = 1_000_000.0;
        remainingDistance16 = location16.distanceSquaredTo(target);
        totalScore16 = distance16 + remainingDistance16;
        location17 = location3.add(Direction.SOUTHEAST);
        distance17 = 1_000_000.0;
        remainingDistance17 = location17.distanceSquaredTo(target);
        totalScore17 = distance17 + remainingDistance17;
        location19 = location4.add(Direction.NORTHWEST);
        distance19 = 1_000_000.0;
        remainingDistance19 = location19.distanceSquaredTo(target);
        totalScore19 = distance19 + remainingDistance19;
        location20 = location4.add(Direction.NORTHEAST);
        distance20 = 1_000_000.0;
        remainingDistance20 = location20.distanceSquaredTo(target);
        totalScore20 = distance20 + remainingDistance20;

        if (blockedDirection != Direction.WEST && rc.canMove(Direction.WEST)) {
            distance1 = myLocation.distanceSquaredTo(location1);
            direction1 = Direction.WEST;
            totalScore1 = distance1 + remainingDistance1;
        }
        if (blockedDirection != Direction.EAST && rc.canMove(Direction.EAST)) {
            distance2 = myLocation.distanceSquaredTo(location2);
            direction2 = Direction.EAST;
            totalScore2 = distance2 + remainingDistance2;
        }
        if (blockedDirection != Direction.SOUTH && rc.canMove(Direction.SOUTH)) {
            distance3 = myLocation.distanceSquaredTo(location3);
            direction3 = Direction.SOUTH;
            totalScore3 = distance3 + remainingDistance3;
        }
        if (blockedDirection != Direction.NORTH && rc.canMove(Direction.NORTH)) {
            distance4 = myLocation.distanceSquaredTo(location4);
            direction4 = Direction.NORTH;
            totalScore4 = distance4 + remainingDistance4;
        }
        if (blockedDirection != Direction.SOUTHWEST && rc.canMove(Direction.SOUTHWEST)) {
            distance5 = myLocation.distanceSquaredTo(location5);
            direction5 = Direction.SOUTHWEST;
            totalScore5 = distance5 + remainingDistance5;
        }
        if (blockedDirection != Direction.NORTHWEST && rc.canMove(Direction.NORTHWEST)) {
            distance6 = myLocation.distanceSquaredTo(location6);
            direction6 = Direction.NORTHWEST;
            totalScore6 = distance6 + remainingDistance6;
        }
        if (blockedDirection != Direction.SOUTHEAST && rc.canMove(Direction.SOUTHEAST)) {
            distance7 = myLocation.distanceSquaredTo(location7);
            direction7 = Direction.SOUTHEAST;
            totalScore7 = distance7 + remainingDistance7;
        }
        if (blockedDirection != Direction.NORTHEAST && rc.canMove(Direction.NORTHEAST)) {
            distance8 = myLocation.distanceSquaredTo(location8);
            direction8 = Direction.NORTHEAST;
            totalScore8 = distance8 + remainingDistance8;
        }
        switch (myX) {
            case 0:
            case 1:
                break;
            default:
                int weight0 = location1.distanceSquaredTo(location9);
                if (distance1 + weight0 < distance9) {
                    distance9 = distance1 + weight0;
                    direction9 = direction1;
                    totalScore9 = distance9 + remainingDistance9;
                }
                int weight1 = location5.distanceSquaredTo(location9);
                if (distance5 + weight1 < distance9) {
                    distance9 = distance5 + weight1;
                    direction9 = direction5;
                    totalScore9 = distance9 + remainingDistance9;
                }
                int weight2 = location6.distanceSquaredTo(location9);
                if (distance6 + weight2 < distance9) {
                    distance9 = distance6 + weight2;
                    direction9 = direction6;
                    totalScore9 = distance9 + remainingDistance9;
                }
        }
        switch (xOffset) {
            case 0:
            case 1:
            case 2:
                break;
            default:
                int weight0 = location2.distanceSquaredTo(location12);
                if (distance2 + weight0 < distance12) {
                    distance12 = distance2 + weight0;
                    direction12 = direction2;
                    totalScore12 = distance12 + remainingDistance12;
                }
                int weight1 = location7.distanceSquaredTo(location12);
                if (distance7 + weight1 < distance12) {
                    distance12 = distance7 + weight1;
                    direction12 = direction7;
                    totalScore12 = distance12 + remainingDistance12;
                }
                int weight2 = location8.distanceSquaredTo(location12);
                if (distance8 + weight2 < distance12) {
                    distance12 = distance8 + weight2;
                    direction12 = direction8;
                    totalScore12 = distance12 + remainingDistance12;
                }
        }
        switch (myY) {
            case 0:
            case 1:
                break;
            default:
                int weight0 = location3.distanceSquaredTo(location15);
                if (distance3 + weight0 < distance15) {
                    distance15 = distance3 + weight0;
                    direction15 = direction3;
                    totalScore15 = distance15 + remainingDistance15;
                }
                int weight1 = location5.distanceSquaredTo(location15);
                if (distance5 + weight1 < distance15) {
                    distance15 = distance5 + weight1;
                    direction15 = direction5;
                    totalScore15 = distance15 + remainingDistance15;
                }
                int weight2 = location7.distanceSquaredTo(location15);
                if (distance7 + weight2 < distance15) {
                    distance15 = distance7 + weight2;
                    direction15 = direction7;
                    totalScore15 = distance15 + remainingDistance15;
                }
        }
        switch (yOffset) {
            case 0:
            case 1:
            case 2:
                break;
            default:
                int weight0 = location4.distanceSquaredTo(location18);
                if (distance4 + weight0 < distance18) {
                    distance18 = distance4 + weight0;
                    direction18 = direction4;
                    totalScore18 = distance18 + remainingDistance18;
                }
                int weight1 = location6.distanceSquaredTo(location18);
                if (distance6 + weight1 < distance18) {
                    distance18 = distance6 + weight1;
                    direction18 = direction6;
                    totalScore18 = distance18 + remainingDistance18;
                }
                int weight2 = location8.distanceSquaredTo(location18);
                if (distance8 + weight2 < distance18) {
                    distance18 = distance8 + weight2;
                    direction18 = direction8;
                    totalScore18 = distance18 + remainingDistance18;
                }
        }
        switch (myX) {
            case 0:
            case 1:
                break;
            default:
                switch (myY) {
                    case 0:
                        break;
                    default:
                        int weight0 = location5.distanceSquaredTo(location10);
                        if (distance5 + weight0 < distance10) {
                            distance10 = distance5 + weight0;
                            direction10 = direction5;
                            totalScore10 = distance10 + remainingDistance10;
                        }
                        int weight1 = location9.distanceSquaredTo(location10);
                        if (distance9 + weight1 < distance10) {
                            distance10 = distance9 + weight1;
                            direction10 = direction9;
                            totalScore10 = distance10 + remainingDistance10;
                        }
                        int weight2 = location1.distanceSquaredTo(location10);
                        if (distance1 + weight2 < distance10) {
                            distance10 = distance1 + weight2;
                            direction10 = direction1;
                            totalScore10 = distance10 + remainingDistance10;
                        }
                }
        }
        switch (myX) {
            case 0:
            case 1:
                break;
            default:
                switch (yOffset) {
                    case 0:
                    case 1:
                        break;
                    default:
                        int weight0 = location6.distanceSquaredTo(location11);
                        if (distance6 + weight0 < distance11) {
                            distance11 = distance6 + weight0;
                            direction11 = direction6;
                            totalScore11 = distance11 + remainingDistance11;
                        }
                        int weight1 = location9.distanceSquaredTo(location11);
                        if (distance9 + weight1 < distance11) {
                            distance11 = distance9 + weight1;
                            direction11 = direction9;
                            totalScore11 = distance11 + remainingDistance11;
                        }
                        int weight2 = location1.distanceSquaredTo(location11);
                        if (distance1 + weight2 < distance11) {
                            distance11 = distance1 + weight2;
                            direction11 = direction1;
                            totalScore11 = distance11 + remainingDistance11;
                        }
                }
        }
        switch (xOffset) {
            case 0:
            case 1:
            case 2:
                break;
            default:
                switch (myY) {
                    case 0:
                        break;
                    default:
                        int weight0 = location7.distanceSquaredTo(location13);
                        if (distance7 + weight0 < distance13) {
                            distance13 = distance7 + weight0;
                            direction13 = direction7;
                            totalScore13 = distance13 + remainingDistance13;
                        }
                        int weight1 = location12.distanceSquaredTo(location13);
                        if (distance12 + weight1 < distance13) {
                            distance13 = distance12 + weight1;
                            direction13 = direction12;
                            totalScore13 = distance13 + remainingDistance13;
                        }
                        int weight2 = location2.distanceSquaredTo(location13);
                        if (distance2 + weight2 < distance13) {
                            distance13 = distance2 + weight2;
                            direction13 = direction2;
                            totalScore13 = distance13 + remainingDistance13;
                        }
                }
        }
        switch (xOffset) {
            case 0:
            case 1:
            case 2:
                break;
            default:
                switch (yOffset) {
                    case 0:
                    case 1:
                        break;
                    default:
                        int weight0 = location8.distanceSquaredTo(location14);
                        if (distance8 + weight0 < distance14) {
                            distance14 = distance8 + weight0;
                            direction14 = direction8;
                            totalScore14 = distance14 + remainingDistance14;
                        }
                        int weight1 = location12.distanceSquaredTo(location14);
                        if (distance12 + weight1 < distance14) {
                            distance14 = distance12 + weight1;
                            direction14 = direction12;
                            totalScore14 = distance14 + remainingDistance14;
                        }
                        int weight2 = location2.distanceSquaredTo(location14);
                        if (distance2 + weight2 < distance14) {
                            distance14 = distance2 + weight2;
                            direction14 = direction2;
                            totalScore14 = distance14 + remainingDistance14;
                        }
                }
        }
        switch (myX) {
            case 0:
                break;
            default:
                switch (myY) {
                    case 0:
                    case 1:
                        break;
                    default:
                        int weight0 = location15.distanceSquaredTo(location16);
                        if (distance15 + weight0 < distance16) {
                            distance16 = distance15 + weight0;
                            direction16 = direction15;
                            totalScore16 = distance16 + remainingDistance16;
                        }
                        int weight1 = location5.distanceSquaredTo(location16);
                        if (distance5 + weight1 < distance16) {
                            distance16 = distance5 + weight1;
                            direction16 = direction5;
                            totalScore16 = distance16 + remainingDistance16;
                        }
                        int weight2 = location3.distanceSquaredTo(location16);
                        if (distance3 + weight2 < distance16) {
                            distance16 = distance3 + weight2;
                            direction16 = direction3;
                            totalScore16 = distance16 + remainingDistance16;
                        }
                }
        }
        switch (xOffset) {
            case 0:
            case 1:
                break;
            default:
                switch (myY) {
                    case 0:
                    case 1:
                        break;
                    default:
                        int weight0 = location15.distanceSquaredTo(location17);
                        if (distance15 + weight0 < distance17) {
                            distance17 = distance15 + weight0;
                            direction17 = direction15;
                            totalScore17 = distance17 + remainingDistance17;
                        }
                        int weight1 = location7.distanceSquaredTo(location17);
                        if (distance7 + weight1 < distance17) {
                            distance17 = distance7 + weight1;
                            direction17 = direction7;
                            totalScore17 = distance17 + remainingDistance17;
                        }
                        int weight2 = location3.distanceSquaredTo(location17);
                        if (distance3 + weight2 < distance17) {
                            distance17 = distance3 + weight2;
                            direction17 = direction3;
                            totalScore17 = distance17 + remainingDistance17;
                        }
                }
        }
        switch (myX) {
            case 0:
                break;
            default:
                switch (yOffset) {
                    case 0:
                    case 1:
                    case 2:
                        break;
                    default:
                        int weight0 = location18.distanceSquaredTo(location19);
                        if (distance18 + weight0 < distance19) {
                            distance19 = distance18 + weight0;
                            direction19 = direction18;
                            totalScore19 = distance19 + remainingDistance19;
                        }
                        int weight1 = location6.distanceSquaredTo(location19);
                        if (distance6 + weight1 < distance19) {
                            distance19 = distance6 + weight1;
                            direction19 = direction6;
                            totalScore19 = distance19 + remainingDistance19;
                        }
                        int weight2 = location4.distanceSquaredTo(location19);
                        if (distance4 + weight2 < distance19) {
                            distance19 = distance4 + weight2;
                            direction19 = direction4;
                            totalScore19 = distance19 + remainingDistance19;
                        }
                }
        }
        switch (xOffset) {
            case 0:
            case 1:
                break;
            default:
                switch (yOffset) {
                    case 0:
                    case 1:
                    case 2:
                        break;
                    default:
                        int weight0 = location18.distanceSquaredTo(location20);
                        if (distance18 + weight0 < distance20) {
                            distance20 = distance18 + weight0;
                            direction20 = direction18;
                            totalScore20 = distance20 + remainingDistance20;
                        }
                        int weight1 = location8.distanceSquaredTo(location20);
                        if (distance8 + weight1 < distance20) {
                            distance20 = distance8 + weight1;
                            direction20 = direction8;
                            totalScore20 = distance20 + remainingDistance20;
                        }
                        int weight2 = location4.distanceSquaredTo(location20);
                        if (distance4 + weight2 < distance20) {
                            distance20 = distance4 + weight2;
                            direction20 = direction4;
                            totalScore20 = distance20 + remainingDistance20;
                        }
                }
        }

        switch (target.x - myX) {
            case -2:
                switch (target.y - myY) {
                    case -1:
                        return direction10;
                    case 0:
                        return direction9;
                    case 1:
                        return direction11;
                }
                break;
            case -1:
                switch (target.y - myY) {
                    case -2:
                        return direction16;
                    case -1:
                        return direction5;
                    case 0:
                        return direction1;
                    case 1:
                        return direction6;
                    case 2:
                        return direction19;
                }
                break;
            case 0:
                switch (target.y - myY) {
                    case -2:
                        return direction15;
                    case -1:
                        return direction3;
                    case 1:
                        return direction4;
                    case 2:
                        return direction18;
                }
                break;
            case 1:
                switch (target.y - myY) {
                    case -2:
                        return direction17;
                    case -1:
                        return direction7;
                    case 0:
                        return direction2;
                    case 1:
                        return direction8;
                    case 2:
                        return direction20;
                }
                break;
            case 2:
                switch (target.y - myY) {
                    case -1:
                        return direction13;
                    case 0:
                        return direction12;
                    case 1:
                        return direction14;
                }
                break;
        }

        currentDistance = myLocation.distanceSquaredTo(target);

        // score5 = (currentDistance - location5.distanceSquaredTo(target)) / distance5;
        score5 = totalScore5;
        // score6 = (currentDistance - location6.distanceSquaredTo(target)) / distance6;
        score6 = totalScore6;
        // score7 = (currentDistance - location7.distanceSquaredTo(target)) / distance7;
        score7 = totalScore7;
        // score8 = (currentDistance - location8.distanceSquaredTo(target)) / distance8;
        score8 = totalScore8;
        // score9 = (currentDistance - location9.distanceSquaredTo(target)) / distance9;
        score9 = totalScore9;
        // score12 = (currentDistance - location12.distanceSquaredTo(target)) / distance12;
        score12 = totalScore12;
        // score15 = (currentDistance - location15.distanceSquaredTo(target)) / distance15;
        score15 = totalScore15;
        // score18 = (currentDistance - location18.distanceSquaredTo(target)) / distance18;
        score18 = totalScore18;
        // score10 = (currentDistance - location10.distanceSquaredTo(target)) / distance10;
        score10 = totalScore10;
        // score11 = (currentDistance - location11.distanceSquaredTo(target)) / distance11;
        score11 = totalScore11;
        // score13 = (currentDistance - location13.distanceSquaredTo(target)) / distance13;
        score13 = totalScore13;
        // score14 = (currentDistance - location14.distanceSquaredTo(target)) / distance14;
        score14 = totalScore14;
        // score16 = (currentDistance - location16.distanceSquaredTo(target)) / distance16;
        score16 = totalScore16;
        // score17 = (currentDistance - location17.distanceSquaredTo(target)) / distance17;
        score17 = totalScore17;
        // score19 = (currentDistance - location19.distanceSquaredTo(target)) / distance19;
        score19 = totalScore19;

        maxScore = Math.max(Math.max(Math.max(Math.max(Math.max(Math.max(Math.max(Math.max(Math.max(Math.max(Math.max(Math.max(Math.max(Math.max(Math.max(score5, score6), score7), score8), score9), score12), score15), score18), score10), score11), score13), score14), score16), score17), score19), (currentDistance - location20.distanceSquaredTo(target)) / distance20);

        if (maxScore == score5) {
            return direction5;
        }
        if (maxScore == score6) {
            return direction6;
        }
        if (maxScore == score7) {
            return direction7;
        }
        if (maxScore == score8) {
            return direction8;
        }
        if (maxScore == score9) {
            return direction9;
        }
        if (maxScore == score12) {
            return direction12;
        }
        if (maxScore == score15) {
            return direction15;
        }
        if (maxScore == score18) {
            return direction18;
        }
        if (maxScore == score10) {
            return direction10;
        }
        if (maxScore == score11) {
            return direction11;
        }
        if (maxScore == score13) {
            return direction13;
        }
        if (maxScore == score14) {
            return direction14;
        }
        if (maxScore == score16) {
            return direction16;
        }
        if (maxScore == score17) {
            return direction17;
        }
        if (maxScore == score19) {
            return direction19;
        }

        return direction20;
    }
}
