package warrior;

import battlecode.common.Direction;
import battlecode.common.GameActionException;
import battlecode.common.MapLocation;
import battlecode.common.RobotController;

// Generated by scripts/dijkstra.py
// Based on Malott Fat Cats's 2021 pathfinding
// Malott Fat Cats's 2021 post-mortem: https://www.battlecode.org/files/postmortem-2021-malott-fat-cats.pdf
public class Dijkstra13 {
    private static RobotController rc;

    private static int mapWidth;
    private static int mapHeight;

    private static MapLocation myLocation;
    private static int myX;
    private static int myY;
    private static int xOffset;
    private static int yOffset;

    private static MapLocation location1;
    private static double distance1;
    private static Direction direction1;
    private static double remainingDistance1;
    private static double totalScore1;
    private static MapLocation location2;
    private static double distance2;
    private static Direction direction2;
    private static double remainingDistance2;
    private static double totalScore2;
    private static MapLocation location3;
    private static double distance3;
    private static Direction direction3;
    private static double remainingDistance3;
    private static double totalScore3;
    private static MapLocation location4;
    private static double distance4;
    private static Direction direction4;
    private static double remainingDistance4;
    private static double totalScore4;
    private static MapLocation location5;
    private static double distance5;
    private static Direction direction5;
    private static double remainingDistance5;
    private static double totalScore5;
    private static MapLocation location6;
    private static double distance6;
    private static Direction direction6;
    private static double remainingDistance6;
    private static double totalScore6;
    private static MapLocation location7;
    private static double distance7;
    private static Direction direction7;
    private static double remainingDistance7;
    private static double totalScore7;
    private static MapLocation location8;
    private static double distance8;
    private static Direction direction8;
    private static double remainingDistance8;
    private static double totalScore8;
    private static MapLocation location9;
    private static double distance9;
    private static Direction direction9;
    private static double remainingDistance9;
    private static double totalScore9;
    private static MapLocation location12;
    private static double distance12;
    private static Direction direction12;
    private static double remainingDistance12;
    private static double totalScore12;
    private static MapLocation location15;
    private static double distance15;
    private static Direction direction15;
    private static double remainingDistance15;
    private static double totalScore15;
    private static MapLocation location18;
    private static double distance18;
    private static Direction direction18;
    private static double remainingDistance18;
    private static double totalScore18;
    private static MapLocation location10;
    private static double distance10;
    private static Direction direction10;
    private static double remainingDistance10;
    private static double totalScore10;
    private static MapLocation location11;
    private static double distance11;
    private static Direction direction11;
    private static double remainingDistance11;
    private static double totalScore11;
    private static MapLocation location13;
    private static double distance13;
    private static Direction direction13;
    private static double remainingDistance13;
    private static double totalScore13;
    private static MapLocation location14;
    private static double distance14;
    private static Direction direction14;
    private static double remainingDistance14;
    private static double totalScore14;
    private static MapLocation location16;
    private static double distance16;
    private static Direction direction16;
    private static double remainingDistance16;
    private static double totalScore16;
    private static MapLocation location17;
    private static double distance17;
    private static Direction direction17;
    private static double remainingDistance17;
    private static double totalScore17;
    private static MapLocation location19;
    private static double distance19;
    private static Direction direction19;
    private static double remainingDistance19;
    private static double totalScore19;
    private static MapLocation location20;
    private static double distance20;
    private static Direction direction20;
    private static double remainingDistance20;
    private static double totalScore20;
    private static MapLocation location21;
    private static double distance21;
    private static Direction direction21;
    private static double remainingDistance21;
    private static double totalScore21;
    private static MapLocation location22;
    private static double distance22;
    private static Direction direction22;
    private static double remainingDistance22;
    private static double totalScore22;
    private static MapLocation location23;
    private static double distance23;
    private static Direction direction23;
    private static double remainingDistance23;
    private static double totalScore23;
    private static MapLocation location24;
    private static double distance24;
    private static Direction direction24;
    private static double remainingDistance24;
    private static double totalScore24;
    private static MapLocation location25;
    private static double distance25;
    private static Direction direction25;
    private static double remainingDistance25;
    private static double totalScore25;
    private static MapLocation location30;
    private static double distance30;
    private static Direction direction30;
    private static double remainingDistance30;
    private static double totalScore30;
    private static MapLocation location35;
    private static double distance35;
    private static Direction direction35;
    private static double remainingDistance35;
    private static double totalScore35;
    private static MapLocation location40;
    private static double distance40;
    private static Direction direction40;
    private static double remainingDistance40;
    private static double totalScore40;
    private static MapLocation location26;
    private static double distance26;
    private static Direction direction26;
    private static double remainingDistance26;
    private static double totalScore26;
    private static MapLocation location27;
    private static double distance27;
    private static Direction direction27;
    private static double remainingDistance27;
    private static double totalScore27;
    private static MapLocation location31;
    private static double distance31;
    private static Direction direction31;
    private static double remainingDistance31;
    private static double totalScore31;
    private static MapLocation location32;
    private static double distance32;
    private static Direction direction32;
    private static double remainingDistance32;
    private static double totalScore32;
    private static MapLocation location36;
    private static double distance36;
    private static Direction direction36;
    private static double remainingDistance36;
    private static double totalScore36;
    private static MapLocation location37;
    private static double distance37;
    private static Direction direction37;
    private static double remainingDistance37;
    private static double totalScore37;
    private static MapLocation location41;
    private static double distance41;
    private static Direction direction41;
    private static double remainingDistance41;
    private static double totalScore41;
    private static MapLocation location42;
    private static double distance42;
    private static Direction direction42;
    private static double remainingDistance42;
    private static double totalScore42;
    private static MapLocation location28;
    private static double distance28;
    private static Direction direction28;
    private static double remainingDistance28;
    private static double totalScore28;
    private static MapLocation location29;
    private static double distance29;
    private static Direction direction29;
    private static double remainingDistance29;
    private static double totalScore29;
    private static MapLocation location33;
    private static double distance33;
    private static Direction direction33;
    private static double remainingDistance33;
    private static double totalScore33;
    private static MapLocation location34;
    private static double distance34;
    private static Direction direction34;
    private static double remainingDistance34;
    private static double totalScore34;
    private static MapLocation location38;
    private static double distance38;
    private static Direction direction38;
    private static double remainingDistance38;
    private static double totalScore38;
    private static MapLocation location39;
    private static double distance39;
    private static Direction direction39;
    private static double remainingDistance39;
    private static double totalScore39;
    private static MapLocation location43;
    private static double distance43;
    private static Direction direction43;
    private static double remainingDistance43;
    private static double totalScore43;
    private static MapLocation location44;
    private static double distance44;
    private static Direction direction44;
    private static double remainingDistance44;
    private static double totalScore44;

    private static double weight;

    private static double currentDistance;

    private static double score21;
    private static double score22;
    private static double score23;
    private static double score24;
    private static double score25;
    private static double score30;
    private static double score35;
    private static double score40;
    private static double score26;
    private static double score27;
    private static double score31;
    private static double score32;
    private static double score36;
    private static double score37;
    private static double score41;
    private static double score42;
    private static double score28;
    private static double score29;
    private static double score33;
    private static double score34;
    private static double score38;
    private static double score39;
    private static double score43;

    private static double maxScore;

    public Dijkstra13(RobotController rc) {
        Dijkstra13.rc = rc;

        mapWidth = rc.getMapWidth();
        mapHeight = rc.getMapHeight();
    }

    public Direction getBestDirection(MapLocation target, Direction blockedDirection) throws GameActionException {
        myLocation = rc.getLocation();
        myX = myLocation.x;
        myY = myLocation.y;
        xOffset = mapWidth - myX;
        yOffset = mapHeight - myY;

        location1 = rc.adjacentLocation(Direction.WEST);
        distance1 = 1_000_000.0;
        remainingDistance1 = location1.distanceSquaredTo(target);
        totalScore1 = distance1 + remainingDistance1;
        location2 = rc.adjacentLocation(Direction.EAST);
        distance2 = 1_000_000.0;
        remainingDistance2 = location2.distanceSquaredTo(target);
        totalScore2 = distance2 + remainingDistance2;
        location3 = rc.adjacentLocation(Direction.SOUTH);
        distance3 = 1_000_000.0;
        remainingDistance3 = location3.distanceSquaredTo(target);
        totalScore3 = distance3 + remainingDistance3;
        location4 = rc.adjacentLocation(Direction.NORTH);
        distance4 = 1_000_000.0;
        remainingDistance4 = location4.distanceSquaredTo(target);
        totalScore4 = distance4 + remainingDistance4;
        location5 = rc.adjacentLocation(Direction.SOUTHWEST);
        distance5 = 1_000_000.0;
        remainingDistance5 = location5.distanceSquaredTo(target);
        totalScore5 = distance5 + remainingDistance5;
        location6 = rc.adjacentLocation(Direction.NORTHWEST);
        distance6 = 1_000_000.0;
        remainingDistance6 = location6.distanceSquaredTo(target);
        totalScore6 = distance6 + remainingDistance6;
        location7 = rc.adjacentLocation(Direction.SOUTHEAST);
        distance7 = 1_000_000.0;
        remainingDistance7 = location7.distanceSquaredTo(target);
        totalScore7 = distance7 + remainingDistance7;
        location8 = rc.adjacentLocation(Direction.NORTHEAST);
        distance8 = 1_000_000.0;
        remainingDistance8 = location8.distanceSquaredTo(target);
        totalScore8 = distance8 + remainingDistance8;
        location9 = location1.add(Direction.WEST);
        distance9 = 1_000_000.0;
        remainingDistance9 = location9.distanceSquaredTo(target);
        totalScore9 = distance9 + remainingDistance9;
        location12 = location2.add(Direction.EAST);
        distance12 = 1_000_000.0;
        remainingDistance12 = location12.distanceSquaredTo(target);
        totalScore12 = distance12 + remainingDistance12;
        location15 = location3.add(Direction.SOUTH);
        distance15 = 1_000_000.0;
        remainingDistance15 = location15.distanceSquaredTo(target);
        totalScore15 = distance15 + remainingDistance15;
        location18 = location4.add(Direction.NORTH);
        distance18 = 1_000_000.0;
        remainingDistance18 = location18.distanceSquaredTo(target);
        totalScore18 = distance18 + remainingDistance18;
        location10 = location1.add(Direction.SOUTHWEST);
        distance10 = 1_000_000.0;
        remainingDistance10 = location10.distanceSquaredTo(target);
        totalScore10 = distance10 + remainingDistance10;
        location11 = location1.add(Direction.NORTHWEST);
        distance11 = 1_000_000.0;
        remainingDistance11 = location11.distanceSquaredTo(target);
        totalScore11 = distance11 + remainingDistance11;
        location13 = location2.add(Direction.SOUTHEAST);
        distance13 = 1_000_000.0;
        remainingDistance13 = location13.distanceSquaredTo(target);
        totalScore13 = distance13 + remainingDistance13;
        location14 = location2.add(Direction.NORTHEAST);
        distance14 = 1_000_000.0;
        remainingDistance14 = location14.distanceSquaredTo(target);
        totalScore14 = distance14 + remainingDistance14;
        location16 = location3.add(Direction.SOUTHWEST);
        distance16 = 1_000_000.0;
        remainingDistance16 = location16.distanceSquaredTo(target);
        totalScore16 = distance16 + remainingDistance16;
        location17 = location3.add(Direction.SOUTHEAST);
        distance17 = 1_000_000.0;
        remainingDistance17 = location17.distanceSquaredTo(target);
        totalScore17 = distance17 + remainingDistance17;
        location19 = location4.add(Direction.NORTHWEST);
        distance19 = 1_000_000.0;
        remainingDistance19 = location19.distanceSquaredTo(target);
        totalScore19 = distance19 + remainingDistance19;
        location20 = location4.add(Direction.NORTHEAST);
        distance20 = 1_000_000.0;
        remainingDistance20 = location20.distanceSquaredTo(target);
        totalScore20 = distance20 + remainingDistance20;
        location21 = location5.add(Direction.SOUTHWEST);
        distance21 = 1_000_000.0;
        remainingDistance21 = location21.distanceSquaredTo(target);
        totalScore21 = distance21 + remainingDistance21;
        location22 = location6.add(Direction.NORTHWEST);
        distance22 = 1_000_000.0;
        remainingDistance22 = location22.distanceSquaredTo(target);
        totalScore22 = distance22 + remainingDistance22;
        location23 = location7.add(Direction.SOUTHEAST);
        distance23 = 1_000_000.0;
        remainingDistance23 = location23.distanceSquaredTo(target);
        totalScore23 = distance23 + remainingDistance23;
        location24 = location8.add(Direction.NORTHEAST);
        distance24 = 1_000_000.0;
        remainingDistance24 = location24.distanceSquaredTo(target);
        totalScore24 = distance24 + remainingDistance24;
        location25 = location9.add(Direction.WEST);
        distance25 = 1_000_000.0;
        remainingDistance25 = location25.distanceSquaredTo(target);
        totalScore25 = distance25 + remainingDistance25;
        location30 = location12.add(Direction.EAST);
        distance30 = 1_000_000.0;
        remainingDistance30 = location30.distanceSquaredTo(target);
        totalScore30 = distance30 + remainingDistance30;
        location35 = location15.add(Direction.SOUTH);
        distance35 = 1_000_000.0;
        remainingDistance35 = location35.distanceSquaredTo(target);
        totalScore35 = distance35 + remainingDistance35;
        location40 = location18.add(Direction.NORTH);
        distance40 = 1_000_000.0;
        remainingDistance40 = location40.distanceSquaredTo(target);
        totalScore40 = distance40 + remainingDistance40;
        location26 = location9.add(Direction.SOUTHWEST);
        distance26 = 1_000_000.0;
        remainingDistance26 = location26.distanceSquaredTo(target);
        totalScore26 = distance26 + remainingDistance26;
        location27 = location9.add(Direction.NORTHWEST);
        distance27 = 1_000_000.0;
        remainingDistance27 = location27.distanceSquaredTo(target);
        totalScore27 = distance27 + remainingDistance27;
        location31 = location12.add(Direction.SOUTHEAST);
        distance31 = 1_000_000.0;
        remainingDistance31 = location31.distanceSquaredTo(target);
        totalScore31 = distance31 + remainingDistance31;
        location32 = location12.add(Direction.NORTHEAST);
        distance32 = 1_000_000.0;
        remainingDistance32 = location32.distanceSquaredTo(target);
        totalScore32 = distance32 + remainingDistance32;
        location36 = location15.add(Direction.SOUTHWEST);
        distance36 = 1_000_000.0;
        remainingDistance36 = location36.distanceSquaredTo(target);
        totalScore36 = distance36 + remainingDistance36;
        location37 = location15.add(Direction.SOUTHEAST);
        distance37 = 1_000_000.0;
        remainingDistance37 = location37.distanceSquaredTo(target);
        totalScore37 = distance37 + remainingDistance37;
        location41 = location18.add(Direction.NORTHWEST);
        distance41 = 1_000_000.0;
        remainingDistance41 = location41.distanceSquaredTo(target);
        totalScore41 = distance41 + remainingDistance41;
        location42 = location18.add(Direction.NORTHEAST);
        distance42 = 1_000_000.0;
        remainingDistance42 = location42.distanceSquaredTo(target);
        totalScore42 = distance42 + remainingDistance42;
        location28 = location10.add(Direction.SOUTHWEST);
        distance28 = 1_000_000.0;
        remainingDistance28 = location28.distanceSquaredTo(target);
        totalScore28 = distance28 + remainingDistance28;
        location29 = location11.add(Direction.NORTHWEST);
        distance29 = 1_000_000.0;
        remainingDistance29 = location29.distanceSquaredTo(target);
        totalScore29 = distance29 + remainingDistance29;
        location33 = location13.add(Direction.SOUTHEAST);
        distance33 = 1_000_000.0;
        remainingDistance33 = location33.distanceSquaredTo(target);
        totalScore33 = distance33 + remainingDistance33;
        location34 = location14.add(Direction.NORTHEAST);
        distance34 = 1_000_000.0;
        remainingDistance34 = location34.distanceSquaredTo(target);
        totalScore34 = distance34 + remainingDistance34;
        location38 = location16.add(Direction.SOUTHWEST);
        distance38 = 1_000_000.0;
        remainingDistance38 = location38.distanceSquaredTo(target);
        totalScore38 = distance38 + remainingDistance38;
        location39 = location17.add(Direction.SOUTHEAST);
        distance39 = 1_000_000.0;
        remainingDistance39 = location39.distanceSquaredTo(target);
        totalScore39 = distance39 + remainingDistance39;
        location43 = location19.add(Direction.NORTHWEST);
        distance43 = 1_000_000.0;
        remainingDistance43 = location43.distanceSquaredTo(target);
        totalScore43 = distance43 + remainingDistance43;
        location44 = location20.add(Direction.NORTHEAST);
        distance44 = 1_000_000.0;
        remainingDistance44 = location44.distanceSquaredTo(target);
        totalScore44 = distance44 + remainingDistance44;

        if (blockedDirection != Direction.WEST && rc.canMove(Direction.WEST)) {
            distance1 = myLocation.distanceSquaredTo(location1);
            direction1 = Direction.WEST;
            totalScore1 = distance1 + remainingDistance1;
        }
        if (blockedDirection != Direction.EAST && rc.canMove(Direction.EAST)) {
            distance2 = myLocation.distanceSquaredTo(location2);
            direction2 = Direction.EAST;
            totalScore2 = distance2 + remainingDistance2;
        }
        if (blockedDirection != Direction.SOUTH && rc.canMove(Direction.SOUTH)) {
            distance3 = myLocation.distanceSquaredTo(location3);
            direction3 = Direction.SOUTH;
            totalScore3 = distance3 + remainingDistance3;
        }
        if (blockedDirection != Direction.NORTH && rc.canMove(Direction.NORTH)) {
            distance4 = myLocation.distanceSquaredTo(location4);
            direction4 = Direction.NORTH;
            totalScore4 = distance4 + remainingDistance4;
        }
        if (blockedDirection != Direction.SOUTHWEST && rc.canMove(Direction.SOUTHWEST)) {
            distance5 = myLocation.distanceSquaredTo(location5);
            direction5 = Direction.SOUTHWEST;
            totalScore5 = distance5 + remainingDistance5;
        }
        if (blockedDirection != Direction.NORTHWEST && rc.canMove(Direction.NORTHWEST)) {
            distance6 = myLocation.distanceSquaredTo(location6);
            direction6 = Direction.NORTHWEST;
            totalScore6 = distance6 + remainingDistance6;
        }
        if (blockedDirection != Direction.SOUTHEAST && rc.canMove(Direction.SOUTHEAST)) {
            distance7 = myLocation.distanceSquaredTo(location7);
            direction7 = Direction.SOUTHEAST;
            totalScore7 = distance7 + remainingDistance7;
        }
        if (blockedDirection != Direction.NORTHEAST && rc.canMove(Direction.NORTHEAST)) {
            distance8 = myLocation.distanceSquaredTo(location8);
            direction8 = Direction.NORTHEAST;
            totalScore8 = distance8 + remainingDistance8;
        }
        switch (myX) {
            case 0:
            case 1:
                break;
            default:
                int weight0 = location1.distanceSquaredTo(location9);
                if (distance1 + weight0 < distance9) {
                    distance9 = distance1 + weight0;
                    direction9 = direction1;
                    totalScore9 = distance9 + remainingDistance9;
                }
                int weight1 = location5.distanceSquaredTo(location9);
                if (distance5 + weight1 < distance9) {
                    distance9 = distance5 + weight1;
                    direction9 = direction5;
                    totalScore9 = distance9 + remainingDistance9;
                }
                int weight2 = location6.distanceSquaredTo(location9);
                if (distance6 + weight2 < distance9) {
                    distance9 = distance6 + weight2;
                    direction9 = direction6;
                    totalScore9 = distance9 + remainingDistance9;
                }
        }
        switch (xOffset) {
            case 0:
            case 1:
            case 2:
                break;
            default:
                int weight0 = location2.distanceSquaredTo(location12);
                if (distance2 + weight0 < distance12) {
                    distance12 = distance2 + weight0;
                    direction12 = direction2;
                    totalScore12 = distance12 + remainingDistance12;
                }
                int weight1 = location7.distanceSquaredTo(location12);
                if (distance7 + weight1 < distance12) {
                    distance12 = distance7 + weight1;
                    direction12 = direction7;
                    totalScore12 = distance12 + remainingDistance12;
                }
                int weight2 = location8.distanceSquaredTo(location12);
                if (distance8 + weight2 < distance12) {
                    distance12 = distance8 + weight2;
                    direction12 = direction8;
                    totalScore12 = distance12 + remainingDistance12;
                }
        }
        switch (myY) {
            case 0:
            case 1:
                break;
            default:
                int weight0 = location3.distanceSquaredTo(location15);
                if (distance3 + weight0 < distance15) {
                    distance15 = distance3 + weight0;
                    direction15 = direction3;
                    totalScore15 = distance15 + remainingDistance15;
                }
                int weight1 = location5.distanceSquaredTo(location15);
                if (distance5 + weight1 < distance15) {
                    distance15 = distance5 + weight1;
                    direction15 = direction5;
                    totalScore15 = distance15 + remainingDistance15;
                }
                int weight2 = location7.distanceSquaredTo(location15);
                if (distance7 + weight2 < distance15) {
                    distance15 = distance7 + weight2;
                    direction15 = direction7;
                    totalScore15 = distance15 + remainingDistance15;
                }
        }
        switch (yOffset) {
            case 0:
            case 1:
            case 2:
                break;
            default:
                int weight0 = location4.distanceSquaredTo(location18);
                if (distance4 + weight0 < distance18) {
                    distance18 = distance4 + weight0;
                    direction18 = direction4;
                    totalScore18 = distance18 + remainingDistance18;
                }
                int weight1 = location6.distanceSquaredTo(location18);
                if (distance6 + weight1 < distance18) {
                    distance18 = distance6 + weight1;
                    direction18 = direction6;
                    totalScore18 = distance18 + remainingDistance18;
                }
                int weight2 = location8.distanceSquaredTo(location18);
                if (distance8 + weight2 < distance18) {
                    distance18 = distance8 + weight2;
                    direction18 = direction8;
                    totalScore18 = distance18 + remainingDistance18;
                }
        }
        switch (myX) {
            case 0:
            case 1:
                break;
            default:
                switch (myY) {
                    case 0:
                        break;
                    default:
                        int weight0 = location5.distanceSquaredTo(location10);
                        if (distance5 + weight0 < distance10) {
                            distance10 = distance5 + weight0;
                            direction10 = direction5;
                            totalScore10 = distance10 + remainingDistance10;
                        }
                        int weight1 = location9.distanceSquaredTo(location10);
                        if (distance9 + weight1 < distance10) {
                            distance10 = distance9 + weight1;
                            direction10 = direction9;
                            totalScore10 = distance10 + remainingDistance10;
                        }
                        int weight2 = location1.distanceSquaredTo(location10);
                        if (distance1 + weight2 < distance10) {
                            distance10 = distance1 + weight2;
                            direction10 = direction1;
                            totalScore10 = distance10 + remainingDistance10;
                        }
                }
        }
        switch (myX) {
            case 0:
            case 1:
                break;
            default:
                switch (yOffset) {
                    case 0:
                    case 1:
                        break;
                    default:
                        int weight0 = location6.distanceSquaredTo(location11);
                        if (distance6 + weight0 < distance11) {
                            distance11 = distance6 + weight0;
                            direction11 = direction6;
                            totalScore11 = distance11 + remainingDistance11;
                        }
                        int weight1 = location9.distanceSquaredTo(location11);
                        if (distance9 + weight1 < distance11) {
                            distance11 = distance9 + weight1;
                            direction11 = direction9;
                            totalScore11 = distance11 + remainingDistance11;
                        }
                        int weight2 = location1.distanceSquaredTo(location11);
                        if (distance1 + weight2 < distance11) {
                            distance11 = distance1 + weight2;
                            direction11 = direction1;
                            totalScore11 = distance11 + remainingDistance11;
                        }
                }
        }
        switch (xOffset) {
            case 0:
            case 1:
            case 2:
                break;
            default:
                switch (myY) {
                    case 0:
                        break;
                    default:
                        int weight0 = location7.distanceSquaredTo(location13);
                        if (distance7 + weight0 < distance13) {
                            distance13 = distance7 + weight0;
                            direction13 = direction7;
                            totalScore13 = distance13 + remainingDistance13;
                        }
                        int weight1 = location12.distanceSquaredTo(location13);
                        if (distance12 + weight1 < distance13) {
                            distance13 = distance12 + weight1;
                            direction13 = direction12;
                            totalScore13 = distance13 + remainingDistance13;
                        }
                        int weight2 = location2.distanceSquaredTo(location13);
                        if (distance2 + weight2 < distance13) {
                            distance13 = distance2 + weight2;
                            direction13 = direction2;
                            totalScore13 = distance13 + remainingDistance13;
                        }
                }
        }
        switch (xOffset) {
            case 0:
            case 1:
            case 2:
                break;
            default:
                switch (yOffset) {
                    case 0:
                    case 1:
                        break;
                    default:
                        int weight0 = location8.distanceSquaredTo(location14);
                        if (distance8 + weight0 < distance14) {
                            distance14 = distance8 + weight0;
                            direction14 = direction8;
                            totalScore14 = distance14 + remainingDistance14;
                        }
                        int weight1 = location12.distanceSquaredTo(location14);
                        if (distance12 + weight1 < distance14) {
                            distance14 = distance12 + weight1;
                            direction14 = direction12;
                            totalScore14 = distance14 + remainingDistance14;
                        }
                        int weight2 = location2.distanceSquaredTo(location14);
                        if (distance2 + weight2 < distance14) {
                            distance14 = distance2 + weight2;
                            direction14 = direction2;
                            totalScore14 = distance14 + remainingDistance14;
                        }
                }
        }
        switch (myX) {
            case 0:
                break;
            default:
                switch (myY) {
                    case 0:
                    case 1:
                        break;
                    default:
                        int weight0 = location15.distanceSquaredTo(location16);
                        if (distance15 + weight0 < distance16) {
                            distance16 = distance15 + weight0;
                            direction16 = direction15;
                            totalScore16 = distance16 + remainingDistance16;
                        }
                        int weight1 = location5.distanceSquaredTo(location16);
                        if (distance5 + weight1 < distance16) {
                            distance16 = distance5 + weight1;
                            direction16 = direction5;
                            totalScore16 = distance16 + remainingDistance16;
                        }
                        int weight2 = location3.distanceSquaredTo(location16);
                        if (distance3 + weight2 < distance16) {
                            distance16 = distance3 + weight2;
                            direction16 = direction3;
                            totalScore16 = distance16 + remainingDistance16;
                        }
                }
        }
        switch (xOffset) {
            case 0:
            case 1:
                break;
            default:
                switch (myY) {
                    case 0:
                    case 1:
                        break;
                    default:
                        int weight0 = location15.distanceSquaredTo(location17);
                        if (distance15 + weight0 < distance17) {
                            distance17 = distance15 + weight0;
                            direction17 = direction15;
                            totalScore17 = distance17 + remainingDistance17;
                        }
                        int weight1 = location7.distanceSquaredTo(location17);
                        if (distance7 + weight1 < distance17) {
                            distance17 = distance7 + weight1;
                            direction17 = direction7;
                            totalScore17 = distance17 + remainingDistance17;
                        }
                        int weight2 = location3.distanceSquaredTo(location17);
                        if (distance3 + weight2 < distance17) {
                            distance17 = distance3 + weight2;
                            direction17 = direction3;
                            totalScore17 = distance17 + remainingDistance17;
                        }
                }
        }
        switch (myX) {
            case 0:
                break;
            default:
                switch (yOffset) {
                    case 0:
                    case 1:
                    case 2:
                        break;
                    default:
                        int weight0 = location18.distanceSquaredTo(location19);
                        if (distance18 + weight0 < distance19) {
                            distance19 = distance18 + weight0;
                            direction19 = direction18;
                            totalScore19 = distance19 + remainingDistance19;
                        }
                        int weight1 = location6.distanceSquaredTo(location19);
                        if (distance6 + weight1 < distance19) {
                            distance19 = distance6 + weight1;
                            direction19 = direction6;
                            totalScore19 = distance19 + remainingDistance19;
                        }
                        int weight2 = location4.distanceSquaredTo(location19);
                        if (distance4 + weight2 < distance19) {
                            distance19 = distance4 + weight2;
                            direction19 = direction4;
                            totalScore19 = distance19 + remainingDistance19;
                        }
                }
        }
        switch (xOffset) {
            case 0:
            case 1:
                break;
            default:
                switch (yOffset) {
                    case 0:
                    case 1:
                    case 2:
                        break;
                    default:
                        int weight0 = location18.distanceSquaredTo(location20);
                        if (distance18 + weight0 < distance20) {
                            distance20 = distance18 + weight0;
                            direction20 = direction18;
                            totalScore20 = distance20 + remainingDistance20;
                        }
                        int weight1 = location8.distanceSquaredTo(location20);
                        if (distance8 + weight1 < distance20) {
                            distance20 = distance8 + weight1;
                            direction20 = direction8;
                            totalScore20 = distance20 + remainingDistance20;
                        }
                        int weight2 = location4.distanceSquaredTo(location20);
                        if (distance4 + weight2 < distance20) {
                            distance20 = distance4 + weight2;
                            direction20 = direction4;
                            totalScore20 = distance20 + remainingDistance20;
                        }
                }
        }
        switch (myX) {
            case 0:
            case 1:
                break;
            default:
                switch (myY) {
                    case 0:
                    case 1:
                        break;
                    default:
                        int weight0 = location16.distanceSquaredTo(location21);
                        if (distance16 + weight0 < distance21) {
                            distance21 = distance16 + weight0;
                            direction21 = direction16;
                            totalScore21 = distance21 + remainingDistance21;
                        }
                        int weight1 = location10.distanceSquaredTo(location21);
                        if (distance10 + weight1 < distance21) {
                            distance21 = distance10 + weight1;
                            direction21 = direction10;
                            totalScore21 = distance21 + remainingDistance21;
                        }
                        int weight2 = location5.distanceSquaredTo(location21);
                        if (distance5 + weight2 < distance21) {
                            distance21 = distance5 + weight2;
                            direction21 = direction5;
                            totalScore21 = distance21 + remainingDistance21;
                        }
                }
        }
        switch (myX) {
            case 0:
            case 1:
                break;
            default:
                switch (yOffset) {
                    case 0:
                    case 1:
                    case 2:
                        break;
                    default:
                        int weight0 = location19.distanceSquaredTo(location22);
                        if (distance19 + weight0 < distance22) {
                            distance22 = distance19 + weight0;
                            direction22 = direction19;
                            totalScore22 = distance22 + remainingDistance22;
                        }
                        int weight1 = location11.distanceSquaredTo(location22);
                        if (distance11 + weight1 < distance22) {
                            distance22 = distance11 + weight1;
                            direction22 = direction11;
                            totalScore22 = distance22 + remainingDistance22;
                        }
                        int weight2 = location6.distanceSquaredTo(location22);
                        if (distance6 + weight2 < distance22) {
                            distance22 = distance6 + weight2;
                            direction22 = direction6;
                            totalScore22 = distance22 + remainingDistance22;
                        }
                }
        }
        switch (xOffset) {
            case 0:
            case 1:
            case 2:
                break;
            default:
                switch (myY) {
                    case 0:
                    case 1:
                        break;
                    default:
                        int weight0 = location17.distanceSquaredTo(location23);
                        if (distance17 + weight0 < distance23) {
                            distance23 = distance17 + weight0;
                            direction23 = direction17;
                            totalScore23 = distance23 + remainingDistance23;
                        }
                        int weight1 = location13.distanceSquaredTo(location23);
                        if (distance13 + weight1 < distance23) {
                            distance23 = distance13 + weight1;
                            direction23 = direction13;
                            totalScore23 = distance23 + remainingDistance23;
                        }
                        int weight2 = location7.distanceSquaredTo(location23);
                        if (distance7 + weight2 < distance23) {
                            distance23 = distance7 + weight2;
                            direction23 = direction7;
                            totalScore23 = distance23 + remainingDistance23;
                        }
                }
        }
        switch (xOffset) {
            case 0:
            case 1:
            case 2:
                break;
            default:
                switch (yOffset) {
                    case 0:
                    case 1:
                    case 2:
                        break;
                    default:
                        int weight0 = location20.distanceSquaredTo(location24);
                        if (distance20 + weight0 < distance24) {
                            distance24 = distance20 + weight0;
                            direction24 = direction20;
                            totalScore24 = distance24 + remainingDistance24;
                        }
                        int weight1 = location14.distanceSquaredTo(location24);
                        if (distance14 + weight1 < distance24) {
                            distance24 = distance14 + weight1;
                            direction24 = direction14;
                            totalScore24 = distance24 + remainingDistance24;
                        }
                        int weight2 = location8.distanceSquaredTo(location24);
                        if (distance8 + weight2 < distance24) {
                            distance24 = distance8 + weight2;
                            direction24 = direction8;
                            totalScore24 = distance24 + remainingDistance24;
                        }
                }
        }
        switch (myX) {
            case 0:
            case 1:
            case 2:
                break;
            default:
                int weight0 = location9.distanceSquaredTo(location25);
                if (distance9 + weight0 < distance25) {
                    distance25 = distance9 + weight0;
                    direction25 = direction9;
                    totalScore25 = distance25 + remainingDistance25;
                }
                int weight1 = location10.distanceSquaredTo(location25);
                if (distance10 + weight1 < distance25) {
                    distance25 = distance10 + weight1;
                    direction25 = direction10;
                    totalScore25 = distance25 + remainingDistance25;
                }
                int weight2 = location11.distanceSquaredTo(location25);
                if (distance11 + weight2 < distance25) {
                    distance25 = distance11 + weight2;
                    direction25 = direction11;
                    totalScore25 = distance25 + remainingDistance25;
                }
        }
        switch (xOffset) {
            case 0:
            case 1:
            case 2:
            case 3:
                break;
            default:
                int weight0 = location12.distanceSquaredTo(location30);
                if (distance12 + weight0 < distance30) {
                    distance30 = distance12 + weight0;
                    direction30 = direction12;
                    totalScore30 = distance30 + remainingDistance30;
                }
                int weight1 = location13.distanceSquaredTo(location30);
                if (distance13 + weight1 < distance30) {
                    distance30 = distance13 + weight1;
                    direction30 = direction13;
                    totalScore30 = distance30 + remainingDistance30;
                }
                int weight2 = location14.distanceSquaredTo(location30);
                if (distance14 + weight2 < distance30) {
                    distance30 = distance14 + weight2;
                    direction30 = direction14;
                    totalScore30 = distance30 + remainingDistance30;
                }
        }
        switch (myY) {
            case 0:
            case 1:
            case 2:
                break;
            default:
                int weight0 = location15.distanceSquaredTo(location35);
                if (distance15 + weight0 < distance35) {
                    distance35 = distance15 + weight0;
                    direction35 = direction15;
                    totalScore35 = distance35 + remainingDistance35;
                }
                int weight1 = location16.distanceSquaredTo(location35);
                if (distance16 + weight1 < distance35) {
                    distance35 = distance16 + weight1;
                    direction35 = direction16;
                    totalScore35 = distance35 + remainingDistance35;
                }
                int weight2 = location17.distanceSquaredTo(location35);
                if (distance17 + weight2 < distance35) {
                    distance35 = distance17 + weight2;
                    direction35 = direction17;
                    totalScore35 = distance35 + remainingDistance35;
                }
        }
        switch (yOffset) {
            case 0:
            case 1:
            case 2:
            case 3:
                break;
            default:
                int weight0 = location18.distanceSquaredTo(location40);
                if (distance18 + weight0 < distance40) {
                    distance40 = distance18 + weight0;
                    direction40 = direction18;
                    totalScore40 = distance40 + remainingDistance40;
                }
                int weight1 = location19.distanceSquaredTo(location40);
                if (distance19 + weight1 < distance40) {
                    distance40 = distance19 + weight1;
                    direction40 = direction19;
                    totalScore40 = distance40 + remainingDistance40;
                }
                int weight2 = location20.distanceSquaredTo(location40);
                if (distance20 + weight2 < distance40) {
                    distance40 = distance20 + weight2;
                    direction40 = direction20;
                    totalScore40 = distance40 + remainingDistance40;
                }
        }
        switch (myX) {
            case 0:
            case 1:
            case 2:
                break;
            default:
                switch (myY) {
                    case 0:
                        break;
                    default:
                        int weight0 = location10.distanceSquaredTo(location26);
                        if (distance10 + weight0 < distance26) {
                            distance26 = distance10 + weight0;
                            direction26 = direction10;
                            totalScore26 = distance26 + remainingDistance26;
                        }
                        int weight1 = location25.distanceSquaredTo(location26);
                        if (distance25 + weight1 < distance26) {
                            distance26 = distance25 + weight1;
                            direction26 = direction25;
                            totalScore26 = distance26 + remainingDistance26;
                        }
                        int weight2 = location21.distanceSquaredTo(location26);
                        if (distance21 + weight2 < distance26) {
                            distance26 = distance21 + weight2;
                            direction26 = direction21;
                            totalScore26 = distance26 + remainingDistance26;
                        }
                        int weight3 = location9.distanceSquaredTo(location26);
                        if (distance9 + weight3 < distance26) {
                            distance26 = distance9 + weight3;
                            direction26 = direction9;
                            totalScore26 = distance26 + remainingDistance26;
                        }
                }
        }
        switch (myX) {
            case 0:
            case 1:
            case 2:
                break;
            default:
                switch (yOffset) {
                    case 0:
                    case 1:
                        break;
                    default:
                        int weight0 = location11.distanceSquaredTo(location27);
                        if (distance11 + weight0 < distance27) {
                            distance27 = distance11 + weight0;
                            direction27 = direction11;
                            totalScore27 = distance27 + remainingDistance27;
                        }
                        int weight1 = location25.distanceSquaredTo(location27);
                        if (distance25 + weight1 < distance27) {
                            distance27 = distance25 + weight1;
                            direction27 = direction25;
                            totalScore27 = distance27 + remainingDistance27;
                        }
                        int weight2 = location9.distanceSquaredTo(location27);
                        if (distance9 + weight2 < distance27) {
                            distance27 = distance9 + weight2;
                            direction27 = direction9;
                            totalScore27 = distance27 + remainingDistance27;
                        }
                        int weight3 = location22.distanceSquaredTo(location27);
                        if (distance22 + weight3 < distance27) {
                            distance27 = distance22 + weight3;
                            direction27 = direction22;
                            totalScore27 = distance27 + remainingDistance27;
                        }
                }
        }
        switch (xOffset) {
            case 0:
            case 1:
            case 2:
            case 3:
                break;
            default:
                switch (myY) {
                    case 0:
                        break;
                    default:
                        int weight0 = location13.distanceSquaredTo(location31);
                        if (distance13 + weight0 < distance31) {
                            distance31 = distance13 + weight0;
                            direction31 = direction13;
                            totalScore31 = distance31 + remainingDistance31;
                        }
                        int weight1 = location30.distanceSquaredTo(location31);
                        if (distance30 + weight1 < distance31) {
                            distance31 = distance30 + weight1;
                            direction31 = direction30;
                            totalScore31 = distance31 + remainingDistance31;
                        }
                        int weight2 = location23.distanceSquaredTo(location31);
                        if (distance23 + weight2 < distance31) {
                            distance31 = distance23 + weight2;
                            direction31 = direction23;
                            totalScore31 = distance31 + remainingDistance31;
                        }
                        int weight3 = location12.distanceSquaredTo(location31);
                        if (distance12 + weight3 < distance31) {
                            distance31 = distance12 + weight3;
                            direction31 = direction12;
                            totalScore31 = distance31 + remainingDistance31;
                        }
                }
        }
        switch (xOffset) {
            case 0:
            case 1:
            case 2:
            case 3:
                break;
            default:
                switch (yOffset) {
                    case 0:
                    case 1:
                        break;
                    default:
                        int weight0 = location14.distanceSquaredTo(location32);
                        if (distance14 + weight0 < distance32) {
                            distance32 = distance14 + weight0;
                            direction32 = direction14;
                            totalScore32 = distance32 + remainingDistance32;
                        }
                        int weight1 = location30.distanceSquaredTo(location32);
                        if (distance30 + weight1 < distance32) {
                            distance32 = distance30 + weight1;
                            direction32 = direction30;
                            totalScore32 = distance32 + remainingDistance32;
                        }
                        int weight2 = location12.distanceSquaredTo(location32);
                        if (distance12 + weight2 < distance32) {
                            distance32 = distance12 + weight2;
                            direction32 = direction12;
                            totalScore32 = distance32 + remainingDistance32;
                        }
                        int weight3 = location24.distanceSquaredTo(location32);
                        if (distance24 + weight3 < distance32) {
                            distance32 = distance24 + weight3;
                            direction32 = direction24;
                            totalScore32 = distance32 + remainingDistance32;
                        }
                }
        }
        switch (myX) {
            case 0:
                break;
            default:
                switch (myY) {
                    case 0:
                    case 1:
                    case 2:
                        break;
                    default:
                        int weight0 = location35.distanceSquaredTo(location36);
                        if (distance35 + weight0 < distance36) {
                            distance36 = distance35 + weight0;
                            direction36 = direction35;
                            totalScore36 = distance36 + remainingDistance36;
                        }
                        int weight1 = location16.distanceSquaredTo(location36);
                        if (distance16 + weight1 < distance36) {
                            distance36 = distance16 + weight1;
                            direction36 = direction16;
                            totalScore36 = distance36 + remainingDistance36;
                        }
                        int weight2 = location21.distanceSquaredTo(location36);
                        if (distance21 + weight2 < distance36) {
                            distance36 = distance21 + weight2;
                            direction36 = direction21;
                            totalScore36 = distance36 + remainingDistance36;
                        }
                        int weight3 = location15.distanceSquaredTo(location36);
                        if (distance15 + weight3 < distance36) {
                            distance36 = distance15 + weight3;
                            direction36 = direction15;
                            totalScore36 = distance36 + remainingDistance36;
                        }
                }
        }
        switch (xOffset) {
            case 0:
            case 1:
                break;
            default:
                switch (myY) {
                    case 0:
                    case 1:
                    case 2:
                        break;
                    default:
                        int weight0 = location35.distanceSquaredTo(location37);
                        if (distance35 + weight0 < distance37) {
                            distance37 = distance35 + weight0;
                            direction37 = direction35;
                            totalScore37 = distance37 + remainingDistance37;
                        }
                        int weight1 = location17.distanceSquaredTo(location37);
                        if (distance17 + weight1 < distance37) {
                            distance37 = distance17 + weight1;
                            direction37 = direction17;
                            totalScore37 = distance37 + remainingDistance37;
                        }
                        int weight2 = location15.distanceSquaredTo(location37);
                        if (distance15 + weight2 < distance37) {
                            distance37 = distance15 + weight2;
                            direction37 = direction15;
                            totalScore37 = distance37 + remainingDistance37;
                        }
                        int weight3 = location23.distanceSquaredTo(location37);
                        if (distance23 + weight3 < distance37) {
                            distance37 = distance23 + weight3;
                            direction37 = direction23;
                            totalScore37 = distance37 + remainingDistance37;
                        }
                }
        }
        switch (myX) {
            case 0:
                break;
            default:
                switch (yOffset) {
                    case 0:
                    case 1:
                    case 2:
                    case 3:
                        break;
                    default:
                        int weight0 = location40.distanceSquaredTo(location41);
                        if (distance40 + weight0 < distance41) {
                            distance41 = distance40 + weight0;
                            direction41 = direction40;
                            totalScore41 = distance41 + remainingDistance41;
                        }
                        int weight1 = location19.distanceSquaredTo(location41);
                        if (distance19 + weight1 < distance41) {
                            distance41 = distance19 + weight1;
                            direction41 = direction19;
                            totalScore41 = distance41 + remainingDistance41;
                        }
                        int weight2 = location22.distanceSquaredTo(location41);
                        if (distance22 + weight2 < distance41) {
                            distance41 = distance22 + weight2;
                            direction41 = direction22;
                            totalScore41 = distance41 + remainingDistance41;
                        }
                        int weight3 = location18.distanceSquaredTo(location41);
                        if (distance18 + weight3 < distance41) {
                            distance41 = distance18 + weight3;
                            direction41 = direction18;
                            totalScore41 = distance41 + remainingDistance41;
                        }
                }
        }
        switch (xOffset) {
            case 0:
            case 1:
                break;
            default:
                switch (yOffset) {
                    case 0:
                    case 1:
                    case 2:
                    case 3:
                        break;
                    default:
                        int weight0 = location40.distanceSquaredTo(location42);
                        if (distance40 + weight0 < distance42) {
                            distance42 = distance40 + weight0;
                            direction42 = direction40;
                            totalScore42 = distance42 + remainingDistance42;
                        }
                        int weight1 = location20.distanceSquaredTo(location42);
                        if (distance20 + weight1 < distance42) {
                            distance42 = distance20 + weight1;
                            direction42 = direction20;
                            totalScore42 = distance42 + remainingDistance42;
                        }
                        int weight2 = location18.distanceSquaredTo(location42);
                        if (distance18 + weight2 < distance42) {
                            distance42 = distance18 + weight2;
                            direction42 = direction18;
                            totalScore42 = distance42 + remainingDistance42;
                        }
                        int weight3 = location24.distanceSquaredTo(location42);
                        if (distance24 + weight3 < distance42) {
                            distance42 = distance24 + weight3;
                            direction42 = direction24;
                            totalScore42 = distance42 + remainingDistance42;
                        }
                }
        }
        switch (myX) {
            case 0:
            case 1:
            case 2:
                break;
            default:
                switch (myY) {
                    case 0:
                    case 1:
                        break;
                    default:
                        int weight0 = location21.distanceSquaredTo(location28);
                        if (distance21 + weight0 < distance28) {
                            distance28 = distance21 + weight0;
                            direction28 = direction21;
                            totalScore28 = distance28 + remainingDistance28;
                        }
                        int weight1 = location26.distanceSquaredTo(location28);
                        if (distance26 + weight1 < distance28) {
                            distance28 = distance26 + weight1;
                            direction28 = direction26;
                            totalScore28 = distance28 + remainingDistance28;
                        }
                        int weight2 = location10.distanceSquaredTo(location28);
                        if (distance10 + weight2 < distance28) {
                            distance28 = distance10 + weight2;
                            direction28 = direction10;
                            totalScore28 = distance28 + remainingDistance28;
                        }
                }
        }
        switch (myX) {
            case 0:
            case 1:
            case 2:
                break;
            default:
                switch (yOffset) {
                    case 0:
                    case 1:
                    case 2:
                        break;
                    default:
                        int weight0 = location22.distanceSquaredTo(location29);
                        if (distance22 + weight0 < distance29) {
                            distance29 = distance22 + weight0;
                            direction29 = direction22;
                            totalScore29 = distance29 + remainingDistance29;
                        }
                        int weight1 = location27.distanceSquaredTo(location29);
                        if (distance27 + weight1 < distance29) {
                            distance29 = distance27 + weight1;
                            direction29 = direction27;
                            totalScore29 = distance29 + remainingDistance29;
                        }
                        int weight2 = location11.distanceSquaredTo(location29);
                        if (distance11 + weight2 < distance29) {
                            distance29 = distance11 + weight2;
                            direction29 = direction11;
                            totalScore29 = distance29 + remainingDistance29;
                        }
                }
        }
        switch (xOffset) {
            case 0:
            case 1:
            case 2:
            case 3:
                break;
            default:
                switch (myY) {
                    case 0:
                    case 1:
                        break;
                    default:
                        int weight0 = location23.distanceSquaredTo(location33);
                        if (distance23 + weight0 < distance33) {
                            distance33 = distance23 + weight0;
                            direction33 = direction23;
                            totalScore33 = distance33 + remainingDistance33;
                        }
                        int weight1 = location31.distanceSquaredTo(location33);
                        if (distance31 + weight1 < distance33) {
                            distance33 = distance31 + weight1;
                            direction33 = direction31;
                            totalScore33 = distance33 + remainingDistance33;
                        }
                        int weight2 = location13.distanceSquaredTo(location33);
                        if (distance13 + weight2 < distance33) {
                            distance33 = distance13 + weight2;
                            direction33 = direction13;
                            totalScore33 = distance33 + remainingDistance33;
                        }
                }
        }
        switch (xOffset) {
            case 0:
            case 1:
            case 2:
            case 3:
                break;
            default:
                switch (yOffset) {
                    case 0:
                    case 1:
                    case 2:
                        break;
                    default:
                        int weight0 = location24.distanceSquaredTo(location34);
                        if (distance24 + weight0 < distance34) {
                            distance34 = distance24 + weight0;
                            direction34 = direction24;
                            totalScore34 = distance34 + remainingDistance34;
                        }
                        int weight1 = location32.distanceSquaredTo(location34);
                        if (distance32 + weight1 < distance34) {
                            distance34 = distance32 + weight1;
                            direction34 = direction32;
                            totalScore34 = distance34 + remainingDistance34;
                        }
                        int weight2 = location14.distanceSquaredTo(location34);
                        if (distance14 + weight2 < distance34) {
                            distance34 = distance14 + weight2;
                            direction34 = direction14;
                            totalScore34 = distance34 + remainingDistance34;
                        }
                }
        }
        switch (myX) {
            case 0:
            case 1:
                break;
            default:
                switch (myY) {
                    case 0:
                    case 1:
                    case 2:
                        break;
                    default:
                        int weight0 = location36.distanceSquaredTo(location38);
                        if (distance36 + weight0 < distance38) {
                            distance38 = distance36 + weight0;
                            direction38 = direction36;
                            totalScore38 = distance38 + remainingDistance38;
                        }
                        int weight1 = location21.distanceSquaredTo(location38);
                        if (distance21 + weight1 < distance38) {
                            distance38 = distance21 + weight1;
                            direction38 = direction21;
                            totalScore38 = distance38 + remainingDistance38;
                        }
                        int weight2 = location16.distanceSquaredTo(location38);
                        if (distance16 + weight2 < distance38) {
                            distance38 = distance16 + weight2;
                            direction38 = direction16;
                            totalScore38 = distance38 + remainingDistance38;
                        }
                }
        }
        switch (xOffset) {
            case 0:
            case 1:
            case 2:
                break;
            default:
                switch (myY) {
                    case 0:
                    case 1:
                    case 2:
                        break;
                    default:
                        int weight0 = location37.distanceSquaredTo(location39);
                        if (distance37 + weight0 < distance39) {
                            distance39 = distance37 + weight0;
                            direction39 = direction37;
                            totalScore39 = distance39 + remainingDistance39;
                        }
                        int weight1 = location23.distanceSquaredTo(location39);
                        if (distance23 + weight1 < distance39) {
                            distance39 = distance23 + weight1;
                            direction39 = direction23;
                            totalScore39 = distance39 + remainingDistance39;
                        }
                        int weight2 = location17.distanceSquaredTo(location39);
                        if (distance17 + weight2 < distance39) {
                            distance39 = distance17 + weight2;
                            direction39 = direction17;
                            totalScore39 = distance39 + remainingDistance39;
                        }
                }
        }
        switch (myX) {
            case 0:
            case 1:
                break;
            default:
                switch (yOffset) {
                    case 0:
                    case 1:
                    case 2:
                    case 3:
                        break;
                    default:
                        int weight0 = location41.distanceSquaredTo(location43);
                        if (distance41 + weight0 < distance43) {
                            distance43 = distance41 + weight0;
                            direction43 = direction41;
                            totalScore43 = distance43 + remainingDistance43;
                        }
                        int weight1 = location22.distanceSquaredTo(location43);
                        if (distance22 + weight1 < distance43) {
                            distance43 = distance22 + weight1;
                            direction43 = direction22;
                            totalScore43 = distance43 + remainingDistance43;
                        }
                        int weight2 = location19.distanceSquaredTo(location43);
                        if (distance19 + weight2 < distance43) {
                            distance43 = distance19 + weight2;
                            direction43 = direction19;
                            totalScore43 = distance43 + remainingDistance43;
                        }
                }
        }
        switch (xOffset) {
            case 0:
            case 1:
            case 2:
                break;
            default:
                switch (yOffset) {
                    case 0:
                    case 1:
                    case 2:
                    case 3:
                        break;
                    default:
                        int weight0 = location42.distanceSquaredTo(location44);
                        if (distance42 + weight0 < distance44) {
                            distance44 = distance42 + weight0;
                            direction44 = direction42;
                            totalScore44 = distance44 + remainingDistance44;
                        }
                        int weight1 = location24.distanceSquaredTo(location44);
                        if (distance24 + weight1 < distance44) {
                            distance44 = distance24 + weight1;
                            direction44 = direction24;
                            totalScore44 = distance44 + remainingDistance44;
                        }
                        int weight2 = location20.distanceSquaredTo(location44);
                        if (distance20 + weight2 < distance44) {
                            distance44 = distance20 + weight2;
                            direction44 = direction20;
                            totalScore44 = distance44 + remainingDistance44;
                        }
                }
        }

        switch (target.x - myX) {
            case -3:
                switch (target.y - myY) {
                    case -2:
                        return direction28;
                    case -1:
                        return direction26;
                    case 0:
                        return direction25;
                    case 1:
                        return direction27;
                    case 2:
                        return direction29;
                }
                break;
            case -2:
                switch (target.y - myY) {
                    case -3:
                        return direction38;
                    case -2:
                        return direction21;
                    case -1:
                        return direction10;
                    case 0:
                        return direction9;
                    case 1:
                        return direction11;
                    case 2:
                        return direction22;
                    case 3:
                        return direction43;
                }
                break;
            case -1:
                switch (target.y - myY) {
                    case -3:
                        return direction36;
                    case -2:
                        return direction16;
                    case -1:
                        return direction5;
                    case 0:
                        return direction1;
                    case 1:
                        return direction6;
                    case 2:
                        return direction19;
                    case 3:
                        return direction41;
                }
                break;
            case 0:
                switch (target.y - myY) {
                    case -3:
                        return direction35;
                    case -2:
                        return direction15;
                    case -1:
                        return direction3;
                    case 1:
                        return direction4;
                    case 2:
                        return direction18;
                    case 3:
                        return direction40;
                }
                break;
            case 1:
                switch (target.y - myY) {
                    case -3:
                        return direction37;
                    case -2:
                        return direction17;
                    case -1:
                        return direction7;
                    case 0:
                        return direction2;
                    case 1:
                        return direction8;
                    case 2:
                        return direction20;
                    case 3:
                        return direction42;
                }
                break;
            case 2:
                switch (target.y - myY) {
                    case -3:
                        return direction39;
                    case -2:
                        return direction23;
                    case -1:
                        return direction13;
                    case 0:
                        return direction12;
                    case 1:
                        return direction14;
                    case 2:
                        return direction24;
                    case 3:
                        return direction44;
                }
                break;
            case 3:
                switch (target.y - myY) {
                    case -2:
                        return direction33;
                    case -1:
                        return direction31;
                    case 0:
                        return direction30;
                    case 1:
                        return direction32;
                    case 2:
                        return direction34;
                }
                break;
        }

        currentDistance = myLocation.distanceSquaredTo(target);

        // score21 = (currentDistance - location21.distanceSquaredTo(target)) / distance21;
        score21 = totalScore21;
        // score22 = (currentDistance - location22.distanceSquaredTo(target)) / distance22;
        score22 = totalScore22;
        // score23 = (currentDistance - location23.distanceSquaredTo(target)) / distance23;
        score23 = totalScore23;
        // score24 = (currentDistance - location24.distanceSquaredTo(target)) / distance24;
        score24 = totalScore24;
        // score25 = (currentDistance - location25.distanceSquaredTo(target)) / distance25;
        score25 = totalScore25;
        // score30 = (currentDistance - location30.distanceSquaredTo(target)) / distance30;
        score30 = totalScore30;
        // score35 = (currentDistance - location35.distanceSquaredTo(target)) / distance35;
        score35 = totalScore35;
        // score40 = (currentDistance - location40.distanceSquaredTo(target)) / distance40;
        score40 = totalScore40;
        // score26 = (currentDistance - location26.distanceSquaredTo(target)) / distance26;
        score26 = totalScore26;
        // score27 = (currentDistance - location27.distanceSquaredTo(target)) / distance27;
        score27 = totalScore27;
        // score31 = (currentDistance - location31.distanceSquaredTo(target)) / distance31;
        score31 = totalScore31;
        // score32 = (currentDistance - location32.distanceSquaredTo(target)) / distance32;
        score32 = totalScore32;
        // score36 = (currentDistance - location36.distanceSquaredTo(target)) / distance36;
        score36 = totalScore36;
        // score37 = (currentDistance - location37.distanceSquaredTo(target)) / distance37;
        score37 = totalScore37;
        // score41 = (currentDistance - location41.distanceSquaredTo(target)) / distance41;
        score41 = totalScore41;
        // score42 = (currentDistance - location42.distanceSquaredTo(target)) / distance42;
        score42 = totalScore42;
        // score28 = (currentDistance - location28.distanceSquaredTo(target)) / distance28;
        score28 = totalScore28;
        // score29 = (currentDistance - location29.distanceSquaredTo(target)) / distance29;
        score29 = totalScore29;
        // score33 = (currentDistance - location33.distanceSquaredTo(target)) / distance33;
        score33 = totalScore33;
        // score34 = (currentDistance - location34.distanceSquaredTo(target)) / distance34;
        score34 = totalScore34;
        // score38 = (currentDistance - location38.distanceSquaredTo(target)) / distance38;
        score38 = totalScore38;
        // score39 = (currentDistance - location39.distanceSquaredTo(target)) / distance39;
        score39 = totalScore39;
        // score43 = (currentDistance - location43.distanceSquaredTo(target)) / distance43;
        score43 = totalScore43;

        maxScore = Math.max(Math.max(Math.max(Math.max(Math.max(Math.max(Math.max(Math.max(Math.max(Math.max(Math.max(Math.max(Math.max(Math.max(Math.max(Math.max(Math.max(Math.max(Math.max(Math.max(Math.max(Math.max(Math.max(score21, score22), score23), score24), score25), score30), score35), score40), score26), score27), score31), score32), score36), score37), score41), score42), score28), score29), score33), score34), score38), score39), score43), (currentDistance - location44.distanceSquaredTo(target)) / distance44);

        if (maxScore == score21) {
            return direction21;
        }
        if (maxScore == score22) {
            return direction22;
        }
        if (maxScore == score23) {
            return direction23;
        }
        if (maxScore == score24) {
            return direction24;
        }
        if (maxScore == score25) {
            return direction25;
        }
        if (maxScore == score30) {
            return direction30;
        }
        if (maxScore == score35) {
            return direction35;
        }
        if (maxScore == score40) {
            return direction40;
        }
        if (maxScore == score26) {
            return direction26;
        }
        if (maxScore == score27) {
            return direction27;
        }
        if (maxScore == score31) {
            return direction31;
        }
        if (maxScore == score32) {
            return direction32;
        }
        if (maxScore == score36) {
            return direction36;
        }
        if (maxScore == score37) {
            return direction37;
        }
        if (maxScore == score41) {
            return direction41;
        }
        if (maxScore == score42) {
            return direction42;
        }
        if (maxScore == score28) {
            return direction28;
        }
        if (maxScore == score29) {
            return direction29;
        }
        if (maxScore == score33) {
            return direction33;
        }
        if (maxScore == score34) {
            return direction34;
        }
        if (maxScore == score38) {
            return direction38;
        }
        if (maxScore == score39) {
            return direction39;
        }
        if (maxScore == score43) {
            return direction43;
        }

        return direction44;
    }
}
